// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

// @@protoc_insertion_point(imports)

@class bussiness_monitor_item;
@class bussiness_monitor_itemBuilder;
@class bussiness_monitor_request;
@class bussiness_monitor_requestBuilder;
@class bussiness_monitor_request_ak;
@class bussiness_monitor_request_akBuilder;
@class monitor_bussiness_type;
@class monitor_bussiness_typeBuilder;
@class monitor_user_status;
@class monitor_user_statusBuilder;
@class query_bussiness_monitor_switches_ak;
@class query_bussiness_monitor_switches_akBuilder;
@class queue_monitor_infos;
@class queue_monitor_infosBuilder;
@class queue_monitor_request;
@class queue_monitor_requestBuilder;
@class queue_monitor_request_ak;
@class queue_monitor_request_akBuilder;
@class status_monitor_request;
@class status_monitor_requestBuilder;
@class status_monitor_request_ak;
@class status_monitor_request_akBuilder;
@class switch_bussiness_monitor;
@class switch_bussiness_monitorBuilder;



@interface BussinessMonitorRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

#define monitor_bussiness_type_main_type @"mainType"
#define monitor_bussiness_type_sub_type @"subType"
@interface monitor_bussiness_type : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasMainType_:1;
  BOOL hasSubType_:1;
  UInt32 mainType;
  UInt32 subType;
}
- (BOOL) hasMainType;
- (BOOL) hasSubType;
@property (readonly) UInt32 mainType;
@property (readonly) UInt32 subType;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (monitor_bussiness_typeBuilder*) builder;
+ (monitor_bussiness_typeBuilder*) builder;
+ (monitor_bussiness_typeBuilder*) builderWithPrototype:(monitor_bussiness_type*) prototype;
- (monitor_bussiness_typeBuilder*) toBuilder;

+ (monitor_bussiness_type*) parseFromData:(NSData*) data;
+ (monitor_bussiness_type*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (monitor_bussiness_type*) parseFromInputStream:(NSInputStream*) input;
+ (monitor_bussiness_type*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (monitor_bussiness_type*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (monitor_bussiness_type*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface monitor_bussiness_typeBuilder : PBGeneratedMessageBuilder {
@private
  monitor_bussiness_type* resultMonitorBussinessType;
}

- (monitor_bussiness_type*) defaultInstance;

- (monitor_bussiness_typeBuilder*) clear;
- (monitor_bussiness_typeBuilder*) clone;

- (monitor_bussiness_type*) build;
- (monitor_bussiness_type*) buildPartial;

- (monitor_bussiness_typeBuilder*) mergeFrom:(monitor_bussiness_type*) other;
- (monitor_bussiness_typeBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (monitor_bussiness_typeBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasMainType;
- (UInt32) mainType;
- (monitor_bussiness_typeBuilder*) setMainType:(UInt32) value;
- (monitor_bussiness_typeBuilder*) clearMainType;

- (BOOL) hasSubType;
- (UInt32) subType;
- (monitor_bussiness_typeBuilder*) setSubType:(UInt32) value;
- (monitor_bussiness_typeBuilder*) clearSubType;
@end

#define bussiness_monitor_item_bussiness_type @"bussinessType"
#define bussiness_monitor_item_ts @"ts"
#define bussiness_monitor_item_total_time @"totalTime"
#define bussiness_monitor_item_count @"count"
#define bussiness_monitor_item_max_time @"maxTime"
#define bussiness_monitor_item_min_time @"minTime"
#define bussiness_monitor_item_succeed_count @"succeedCount"
#define bussiness_monitor_item_type @"type"
#define bussiness_monitor_item_max_instance_id @"maxInstanceId"
#define bussiness_monitor_item_min_instance_id @"minInstanceId"
@interface bussiness_monitor_item : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasTs_:1;
  BOOL hasBussinessType_:1;
  BOOL hasTotalTime_:1;
  BOOL hasCount_:1;
  BOOL hasMaxTime_:1;
  BOOL hasMinTime_:1;
  BOOL hasSucceedCount_:1;
  BOOL hasType_:1;
  BOOL hasMaxInstanceId_:1;
  BOOL hasMinInstanceId_:1;
  UInt64 ts;
  monitor_bussiness_type* bussinessType;
  UInt32 totalTime;
  UInt32 count;
  UInt32 maxTime;
  UInt32 minTime;
  UInt32 succeedCount;
  UInt32 type;
  UInt32 maxInstanceId;
  UInt32 minInstanceId;
}
- (BOOL) hasBussinessType;
- (BOOL) hasTs;
- (BOOL) hasTotalTime;
- (BOOL) hasCount;
- (BOOL) hasMaxTime;
- (BOOL) hasMinTime;
- (BOOL) hasSucceedCount;
- (BOOL) hasType;
- (BOOL) hasMaxInstanceId;
- (BOOL) hasMinInstanceId;
@property (readonly, strong) monitor_bussiness_type* bussinessType;
@property (readonly) UInt64 ts;
@property (readonly) UInt32 totalTime;
@property (readonly) UInt32 count;
@property (readonly) UInt32 maxTime;
@property (readonly) UInt32 minTime;
@property (readonly) UInt32 succeedCount;
@property (readonly) UInt32 type;
@property (readonly) UInt32 maxInstanceId;
@property (readonly) UInt32 minInstanceId;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (bussiness_monitor_itemBuilder*) builder;
+ (bussiness_monitor_itemBuilder*) builder;
+ (bussiness_monitor_itemBuilder*) builderWithPrototype:(bussiness_monitor_item*) prototype;
- (bussiness_monitor_itemBuilder*) toBuilder;

+ (bussiness_monitor_item*) parseFromData:(NSData*) data;
+ (bussiness_monitor_item*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (bussiness_monitor_item*) parseFromInputStream:(NSInputStream*) input;
+ (bussiness_monitor_item*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (bussiness_monitor_item*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (bussiness_monitor_item*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface bussiness_monitor_itemBuilder : PBGeneratedMessageBuilder {
@private
  bussiness_monitor_item* resultBussinessMonitorItem;
}

- (bussiness_monitor_item*) defaultInstance;

- (bussiness_monitor_itemBuilder*) clear;
- (bussiness_monitor_itemBuilder*) clone;

- (bussiness_monitor_item*) build;
- (bussiness_monitor_item*) buildPartial;

- (bussiness_monitor_itemBuilder*) mergeFrom:(bussiness_monitor_item*) other;
- (bussiness_monitor_itemBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (bussiness_monitor_itemBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasBussinessType;
- (monitor_bussiness_type*) bussinessType;
- (bussiness_monitor_itemBuilder*) setBussinessType:(monitor_bussiness_type*) value;
- (bussiness_monitor_itemBuilder*) setBussinessTypeBuilder:(monitor_bussiness_typeBuilder*) builderForValue;
- (bussiness_monitor_itemBuilder*) mergeBussinessType:(monitor_bussiness_type*) value;
- (bussiness_monitor_itemBuilder*) clearBussinessType;

- (BOOL) hasTs;
- (UInt64) ts;
- (bussiness_monitor_itemBuilder*) setTs:(UInt64) value;
- (bussiness_monitor_itemBuilder*) clearTs;

- (BOOL) hasTotalTime;
- (UInt32) totalTime;
- (bussiness_monitor_itemBuilder*) setTotalTime:(UInt32) value;
- (bussiness_monitor_itemBuilder*) clearTotalTime;

- (BOOL) hasCount;
- (UInt32) count;
- (bussiness_monitor_itemBuilder*) setCount:(UInt32) value;
- (bussiness_monitor_itemBuilder*) clearCount;

- (BOOL) hasMaxTime;
- (UInt32) maxTime;
- (bussiness_monitor_itemBuilder*) setMaxTime:(UInt32) value;
- (bussiness_monitor_itemBuilder*) clearMaxTime;

- (BOOL) hasMinTime;
- (UInt32) minTime;
- (bussiness_monitor_itemBuilder*) setMinTime:(UInt32) value;
- (bussiness_monitor_itemBuilder*) clearMinTime;

- (BOOL) hasSucceedCount;
- (UInt32) succeedCount;
- (bussiness_monitor_itemBuilder*) setSucceedCount:(UInt32) value;
- (bussiness_monitor_itemBuilder*) clearSucceedCount;

- (BOOL) hasType;
- (UInt32) type;
- (bussiness_monitor_itemBuilder*) setType:(UInt32) value;
- (bussiness_monitor_itemBuilder*) clearType;

- (BOOL) hasMaxInstanceId;
- (UInt32) maxInstanceId;
- (bussiness_monitor_itemBuilder*) setMaxInstanceId:(UInt32) value;
- (bussiness_monitor_itemBuilder*) clearMaxInstanceId;

- (BOOL) hasMinInstanceId;
- (UInt32) minInstanceId;
- (bussiness_monitor_itemBuilder*) setMinInstanceId:(UInt32) value;
- (bussiness_monitor_itemBuilder*) clearMinInstanceId;
@end

#define monitor_user_status_user_name @"userName"
#define monitor_user_status_status @"status"
#define monitor_user_status_device_type @"deviceType"
#define monitor_user_status_flag @"flag"
#define monitor_user_status_instance_id @"instanceId"
@interface monitor_user_status : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasUserName_:1;
  BOOL hasStatus_:1;
  BOOL hasDeviceType_:1;
  BOOL hasFlag_:1;
  BOOL hasInstanceId_:1;
  NSString* userName;
  UInt32 status;
  UInt32 deviceType;
  UInt32 flag;
  UInt32 instanceId;
}
- (BOOL) hasUserName;
- (BOOL) hasStatus;
- (BOOL) hasDeviceType;
- (BOOL) hasFlag;
- (BOOL) hasInstanceId;
@property (readonly, strong) NSString* userName;
@property (readonly) UInt32 status;
@property (readonly) UInt32 deviceType;
@property (readonly) UInt32 flag;
@property (readonly) UInt32 instanceId;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (monitor_user_statusBuilder*) builder;
+ (monitor_user_statusBuilder*) builder;
+ (monitor_user_statusBuilder*) builderWithPrototype:(monitor_user_status*) prototype;
- (monitor_user_statusBuilder*) toBuilder;

+ (monitor_user_status*) parseFromData:(NSData*) data;
+ (monitor_user_status*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (monitor_user_status*) parseFromInputStream:(NSInputStream*) input;
+ (monitor_user_status*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (monitor_user_status*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (monitor_user_status*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface monitor_user_statusBuilder : PBGeneratedMessageBuilder {
@private
  monitor_user_status* resultMonitorUserStatus;
}

- (monitor_user_status*) defaultInstance;

- (monitor_user_statusBuilder*) clear;
- (monitor_user_statusBuilder*) clone;

- (monitor_user_status*) build;
- (monitor_user_status*) buildPartial;

- (monitor_user_statusBuilder*) mergeFrom:(monitor_user_status*) other;
- (monitor_user_statusBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (monitor_user_statusBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserName;
- (NSString*) userName;
- (monitor_user_statusBuilder*) setUserName:(NSString*) value;
- (monitor_user_statusBuilder*) clearUserName;

- (BOOL) hasStatus;
- (UInt32) status;
- (monitor_user_statusBuilder*) setStatus:(UInt32) value;
- (monitor_user_statusBuilder*) clearStatus;

- (BOOL) hasDeviceType;
- (UInt32) deviceType;
- (monitor_user_statusBuilder*) setDeviceType:(UInt32) value;
- (monitor_user_statusBuilder*) clearDeviceType;

- (BOOL) hasFlag;
- (UInt32) flag;
- (monitor_user_statusBuilder*) setFlag:(UInt32) value;
- (monitor_user_statusBuilder*) clearFlag;

- (BOOL) hasInstanceId;
- (UInt32) instanceId;
- (monitor_user_statusBuilder*) setInstanceId:(UInt32) value;
- (monitor_user_statusBuilder*) clearInstanceId;
@end

#define queue_monitor_infos_type @"type"
#define queue_monitor_infos_length @"length"
#define queue_monitor_infos_recieve_length @"recieveLength"
#define queue_monitor_infos_send_length @"sendLength"
@interface queue_monitor_infos : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasRecieveLength_:1;
  BOOL hasSendLength_:1;
  BOOL hasType_:1;
  BOOL hasLength_:1;
  UInt64 recieveLength;
  UInt64 sendLength;
  UInt32 type;
  UInt32 length;
}
- (BOOL) hasType;
- (BOOL) hasLength;
- (BOOL) hasRecieveLength;
- (BOOL) hasSendLength;
@property (readonly) UInt32 type;
@property (readonly) UInt32 length;
@property (readonly) UInt64 recieveLength;
@property (readonly) UInt64 sendLength;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (queue_monitor_infosBuilder*) builder;
+ (queue_monitor_infosBuilder*) builder;
+ (queue_monitor_infosBuilder*) builderWithPrototype:(queue_monitor_infos*) prototype;
- (queue_monitor_infosBuilder*) toBuilder;

+ (queue_monitor_infos*) parseFromData:(NSData*) data;
+ (queue_monitor_infos*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (queue_monitor_infos*) parseFromInputStream:(NSInputStream*) input;
+ (queue_monitor_infos*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (queue_monitor_infos*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (queue_monitor_infos*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface queue_monitor_infosBuilder : PBGeneratedMessageBuilder {
@private
  queue_monitor_infos* resultQueueMonitorInfos;
}

- (queue_monitor_infos*) defaultInstance;

- (queue_monitor_infosBuilder*) clear;
- (queue_monitor_infosBuilder*) clone;

- (queue_monitor_infos*) build;
- (queue_monitor_infos*) buildPartial;

- (queue_monitor_infosBuilder*) mergeFrom:(queue_monitor_infos*) other;
- (queue_monitor_infosBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (queue_monitor_infosBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasType;
- (UInt32) type;
- (queue_monitor_infosBuilder*) setType:(UInt32) value;
- (queue_monitor_infosBuilder*) clearType;

- (BOOL) hasLength;
- (UInt32) length;
- (queue_monitor_infosBuilder*) setLength:(UInt32) value;
- (queue_monitor_infosBuilder*) clearLength;

- (BOOL) hasRecieveLength;
- (UInt64) recieveLength;
- (queue_monitor_infosBuilder*) setRecieveLength:(UInt64) value;
- (queue_monitor_infosBuilder*) clearRecieveLength;

- (BOOL) hasSendLength;
- (UInt64) sendLength;
- (queue_monitor_infosBuilder*) setSendLength:(UInt64) value;
- (queue_monitor_infosBuilder*) clearSendLength;
@end

#define switch_bussiness_monitor_switches @"switches"
@interface switch_bussiness_monitor : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasSwitches_:1;
  UInt32 switches;
}
- (BOOL) hasSwitches;
@property (readonly) UInt32 switches;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (switch_bussiness_monitorBuilder*) builder;
+ (switch_bussiness_monitorBuilder*) builder;
+ (switch_bussiness_monitorBuilder*) builderWithPrototype:(switch_bussiness_monitor*) prototype;
- (switch_bussiness_monitorBuilder*) toBuilder;

+ (switch_bussiness_monitor*) parseFromData:(NSData*) data;
+ (switch_bussiness_monitor*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (switch_bussiness_monitor*) parseFromInputStream:(NSInputStream*) input;
+ (switch_bussiness_monitor*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (switch_bussiness_monitor*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (switch_bussiness_monitor*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface switch_bussiness_monitorBuilder : PBGeneratedMessageBuilder {
@private
  switch_bussiness_monitor* resultSwitchBussinessMonitor;
}

- (switch_bussiness_monitor*) defaultInstance;

- (switch_bussiness_monitorBuilder*) clear;
- (switch_bussiness_monitorBuilder*) clone;

- (switch_bussiness_monitor*) build;
- (switch_bussiness_monitor*) buildPartial;

- (switch_bussiness_monitorBuilder*) mergeFrom:(switch_bussiness_monitor*) other;
- (switch_bussiness_monitorBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (switch_bussiness_monitorBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasSwitches;
- (UInt32) switches;
- (switch_bussiness_monitorBuilder*) setSwitches:(UInt32) value;
- (switch_bussiness_monitorBuilder*) clearSwitches;
@end

#define query_bussiness_monitor_switches_ak_switches @"switches"
@interface query_bussiness_monitor_switches_ak : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasSwitches_:1;
  UInt32 switches;
}
- (BOOL) hasSwitches;
@property (readonly) UInt32 switches;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (query_bussiness_monitor_switches_akBuilder*) builder;
+ (query_bussiness_monitor_switches_akBuilder*) builder;
+ (query_bussiness_monitor_switches_akBuilder*) builderWithPrototype:(query_bussiness_monitor_switches_ak*) prototype;
- (query_bussiness_monitor_switches_akBuilder*) toBuilder;

+ (query_bussiness_monitor_switches_ak*) parseFromData:(NSData*) data;
+ (query_bussiness_monitor_switches_ak*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (query_bussiness_monitor_switches_ak*) parseFromInputStream:(NSInputStream*) input;
+ (query_bussiness_monitor_switches_ak*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (query_bussiness_monitor_switches_ak*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (query_bussiness_monitor_switches_ak*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface query_bussiness_monitor_switches_akBuilder : PBGeneratedMessageBuilder {
@private
  query_bussiness_monitor_switches_ak* resultQueryBussinessMonitorSwitchesAk;
}

- (query_bussiness_monitor_switches_ak*) defaultInstance;

- (query_bussiness_monitor_switches_akBuilder*) clear;
- (query_bussiness_monitor_switches_akBuilder*) clone;

- (query_bussiness_monitor_switches_ak*) build;
- (query_bussiness_monitor_switches_ak*) buildPartial;

- (query_bussiness_monitor_switches_akBuilder*) mergeFrom:(query_bussiness_monitor_switches_ak*) other;
- (query_bussiness_monitor_switches_akBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (query_bussiness_monitor_switches_akBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasSwitches;
- (UInt32) switches;
- (query_bussiness_monitor_switches_akBuilder*) setSwitches:(UInt32) value;
- (query_bussiness_monitor_switches_akBuilder*) clearSwitches;
@end

#define bussiness_monitor_request_bussiness_types @"bussinessTypes"
#define bussiness_monitor_request_monitor_type @"monitorType"
@interface bussiness_monitor_request : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasMonitorType_:1;
  UInt32 monitorType;
  NSMutableArray * bussinessTypesArray;
}
- (BOOL) hasMonitorType;
@property (readonly, strong) NSArray<monitor_bussiness_type*> * bussinessTypes;
@property (readonly) UInt32 monitorType;
- (monitor_bussiness_type*)bussinessTypesAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (bussiness_monitor_requestBuilder*) builder;
+ (bussiness_monitor_requestBuilder*) builder;
+ (bussiness_monitor_requestBuilder*) builderWithPrototype:(bussiness_monitor_request*) prototype;
- (bussiness_monitor_requestBuilder*) toBuilder;

+ (bussiness_monitor_request*) parseFromData:(NSData*) data;
+ (bussiness_monitor_request*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (bussiness_monitor_request*) parseFromInputStream:(NSInputStream*) input;
+ (bussiness_monitor_request*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (bussiness_monitor_request*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (bussiness_monitor_request*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface bussiness_monitor_requestBuilder : PBGeneratedMessageBuilder {
@private
  bussiness_monitor_request* resultBussinessMonitorRequest;
}

- (bussiness_monitor_request*) defaultInstance;

- (bussiness_monitor_requestBuilder*) clear;
- (bussiness_monitor_requestBuilder*) clone;

- (bussiness_monitor_request*) build;
- (bussiness_monitor_request*) buildPartial;

- (bussiness_monitor_requestBuilder*) mergeFrom:(bussiness_monitor_request*) other;
- (bussiness_monitor_requestBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (bussiness_monitor_requestBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSMutableArray<monitor_bussiness_type*> *)bussinessTypes;
- (monitor_bussiness_type*)bussinessTypesAtIndex:(NSUInteger)index;
- (bussiness_monitor_requestBuilder *)addBussinessTypes:(monitor_bussiness_type*)value;
- (bussiness_monitor_requestBuilder *)setBussinessTypesArray:(NSArray<monitor_bussiness_type*> *)array;
- (bussiness_monitor_requestBuilder *)clearBussinessTypes;

- (BOOL) hasMonitorType;
- (UInt32) monitorType;
- (bussiness_monitor_requestBuilder*) setMonitorType:(UInt32) value;
- (bussiness_monitor_requestBuilder*) clearMonitorType;
@end

#define bussiness_monitor_request_ak_items @"items"
@interface bussiness_monitor_request_ak : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  NSMutableArray * itemsArray;
}
@property (readonly, strong) NSArray<bussiness_monitor_item*> * items;
- (bussiness_monitor_item*)itemsAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (bussiness_monitor_request_akBuilder*) builder;
+ (bussiness_monitor_request_akBuilder*) builder;
+ (bussiness_monitor_request_akBuilder*) builderWithPrototype:(bussiness_monitor_request_ak*) prototype;
- (bussiness_monitor_request_akBuilder*) toBuilder;

+ (bussiness_monitor_request_ak*) parseFromData:(NSData*) data;
+ (bussiness_monitor_request_ak*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (bussiness_monitor_request_ak*) parseFromInputStream:(NSInputStream*) input;
+ (bussiness_monitor_request_ak*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (bussiness_monitor_request_ak*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (bussiness_monitor_request_ak*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface bussiness_monitor_request_akBuilder : PBGeneratedMessageBuilder {
@private
  bussiness_monitor_request_ak* resultBussinessMonitorRequestAk;
}

- (bussiness_monitor_request_ak*) defaultInstance;

- (bussiness_monitor_request_akBuilder*) clear;
- (bussiness_monitor_request_akBuilder*) clone;

- (bussiness_monitor_request_ak*) build;
- (bussiness_monitor_request_ak*) buildPartial;

- (bussiness_monitor_request_akBuilder*) mergeFrom:(bussiness_monitor_request_ak*) other;
- (bussiness_monitor_request_akBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (bussiness_monitor_request_akBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSMutableArray<bussiness_monitor_item*> *)items;
- (bussiness_monitor_item*)itemsAtIndex:(NSUInteger)index;
- (bussiness_monitor_request_akBuilder *)addItems:(bussiness_monitor_item*)value;
- (bussiness_monitor_request_akBuilder *)setItemsArray:(NSArray<bussiness_monitor_item*> *)array;
- (bussiness_monitor_request_akBuilder *)clearItems;
@end

#define status_monitor_request_user_names @"userNames"
@interface status_monitor_request : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  NSMutableArray * userNamesArray;
}
@property (readonly, strong) NSArray * userNames;
- (NSString*)userNamesAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (status_monitor_requestBuilder*) builder;
+ (status_monitor_requestBuilder*) builder;
+ (status_monitor_requestBuilder*) builderWithPrototype:(status_monitor_request*) prototype;
- (status_monitor_requestBuilder*) toBuilder;

+ (status_monitor_request*) parseFromData:(NSData*) data;
+ (status_monitor_request*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (status_monitor_request*) parseFromInputStream:(NSInputStream*) input;
+ (status_monitor_request*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (status_monitor_request*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (status_monitor_request*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface status_monitor_requestBuilder : PBGeneratedMessageBuilder {
@private
  status_monitor_request* resultStatusMonitorRequest;
}

- (status_monitor_request*) defaultInstance;

- (status_monitor_requestBuilder*) clear;
- (status_monitor_requestBuilder*) clone;

- (status_monitor_request*) build;
- (status_monitor_request*) buildPartial;

- (status_monitor_requestBuilder*) mergeFrom:(status_monitor_request*) other;
- (status_monitor_requestBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (status_monitor_requestBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSMutableArray *)userNames;
- (NSString*)userNamesAtIndex:(NSUInteger)index;
- (status_monitor_requestBuilder *)addUserNames:(NSString*)value;
- (status_monitor_requestBuilder *)setUserNamesArray:(NSArray *)array;
- (status_monitor_requestBuilder *)clearUserNames;
@end

#define status_monitor_request_ak_user_statuses @"userStatuses"
@interface status_monitor_request_ak : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  NSMutableArray * userStatusesArray;
}
@property (readonly, strong) NSArray<monitor_user_status*> * userStatuses;
- (monitor_user_status*)userStatusesAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (status_monitor_request_akBuilder*) builder;
+ (status_monitor_request_akBuilder*) builder;
+ (status_monitor_request_akBuilder*) builderWithPrototype:(status_monitor_request_ak*) prototype;
- (status_monitor_request_akBuilder*) toBuilder;

+ (status_monitor_request_ak*) parseFromData:(NSData*) data;
+ (status_monitor_request_ak*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (status_monitor_request_ak*) parseFromInputStream:(NSInputStream*) input;
+ (status_monitor_request_ak*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (status_monitor_request_ak*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (status_monitor_request_ak*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface status_monitor_request_akBuilder : PBGeneratedMessageBuilder {
@private
  status_monitor_request_ak* resultStatusMonitorRequestAk;
}

- (status_monitor_request_ak*) defaultInstance;

- (status_monitor_request_akBuilder*) clear;
- (status_monitor_request_akBuilder*) clone;

- (status_monitor_request_ak*) build;
- (status_monitor_request_ak*) buildPartial;

- (status_monitor_request_akBuilder*) mergeFrom:(status_monitor_request_ak*) other;
- (status_monitor_request_akBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (status_monitor_request_akBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSMutableArray<monitor_user_status*> *)userStatuses;
- (monitor_user_status*)userStatusesAtIndex:(NSUInteger)index;
- (status_monitor_request_akBuilder *)addUserStatuses:(monitor_user_status*)value;
- (status_monitor_request_akBuilder *)setUserStatusesArray:(NSArray<monitor_user_status*> *)array;
- (status_monitor_request_akBuilder *)clearUserStatuses;
@end

#define queue_monitor_request_queue_types @"queueTypes"
@interface queue_monitor_request : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  PBAppendableArray * queueTypesArray;
}
@property (readonly, strong) PBArray * queueTypes;
- (UInt32)queueTypesAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (queue_monitor_requestBuilder*) builder;
+ (queue_monitor_requestBuilder*) builder;
+ (queue_monitor_requestBuilder*) builderWithPrototype:(queue_monitor_request*) prototype;
- (queue_monitor_requestBuilder*) toBuilder;

+ (queue_monitor_request*) parseFromData:(NSData*) data;
+ (queue_monitor_request*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (queue_monitor_request*) parseFromInputStream:(NSInputStream*) input;
+ (queue_monitor_request*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (queue_monitor_request*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (queue_monitor_request*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface queue_monitor_requestBuilder : PBGeneratedMessageBuilder {
@private
  queue_monitor_request* resultQueueMonitorRequest;
}

- (queue_monitor_request*) defaultInstance;

- (queue_monitor_requestBuilder*) clear;
- (queue_monitor_requestBuilder*) clone;

- (queue_monitor_request*) build;
- (queue_monitor_request*) buildPartial;

- (queue_monitor_requestBuilder*) mergeFrom:(queue_monitor_request*) other;
- (queue_monitor_requestBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (queue_monitor_requestBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (PBAppendableArray *)queueTypes;
- (UInt32)queueTypesAtIndex:(NSUInteger)index;
- (queue_monitor_requestBuilder *)addQueueTypes:(UInt32)value;
- (queue_monitor_requestBuilder *)setQueueTypesArray:(NSArray *)array;
- (queue_monitor_requestBuilder *)setQueueTypesValues:(const UInt32 *)values count:(NSUInteger)count;
- (queue_monitor_requestBuilder *)clearQueueTypes;
@end

#define queue_monitor_request_ak_queue_infos @"queueInfos"
@interface queue_monitor_request_ak : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  NSMutableArray * queueInfosArray;
}
@property (readonly, strong) NSArray<queue_monitor_infos*> * queueInfos;
- (queue_monitor_infos*)queueInfosAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (queue_monitor_request_akBuilder*) builder;
+ (queue_monitor_request_akBuilder*) builder;
+ (queue_monitor_request_akBuilder*) builderWithPrototype:(queue_monitor_request_ak*) prototype;
- (queue_monitor_request_akBuilder*) toBuilder;

+ (queue_monitor_request_ak*) parseFromData:(NSData*) data;
+ (queue_monitor_request_ak*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (queue_monitor_request_ak*) parseFromInputStream:(NSInputStream*) input;
+ (queue_monitor_request_ak*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (queue_monitor_request_ak*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (queue_monitor_request_ak*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface queue_monitor_request_akBuilder : PBGeneratedMessageBuilder {
@private
  queue_monitor_request_ak* resultQueueMonitorRequestAk;
}

- (queue_monitor_request_ak*) defaultInstance;

- (queue_monitor_request_akBuilder*) clear;
- (queue_monitor_request_akBuilder*) clone;

- (queue_monitor_request_ak*) build;
- (queue_monitor_request_ak*) buildPartial;

- (queue_monitor_request_akBuilder*) mergeFrom:(queue_monitor_request_ak*) other;
- (queue_monitor_request_akBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (queue_monitor_request_akBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSMutableArray<queue_monitor_infos*> *)queueInfos;
- (queue_monitor_infos*)queueInfosAtIndex:(NSUInteger)index;
- (queue_monitor_request_akBuilder *)addQueueInfos:(queue_monitor_infos*)value;
- (queue_monitor_request_akBuilder *)setQueueInfosArray:(NSArray<queue_monitor_infos*> *)array;
- (queue_monitor_request_akBuilder *)clearQueueInfos;
@end


// @@protoc_insertion_point(global_scope)
