# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Proto' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Proto
  pod "ProtocolBuffers", "~> 1.9.7"
  pod "CocoaAsyncSocket"
end
